### ISSUE TITLE
Nil based parser method?

### ISSUE THREAD

**Issue by ray-delossantos** [maiha/jq.cr#1]
Hello @maiha:

Is there any plan in allowing this code pattern?

``` crystal
jq[".xxx"]?.try &.to_i
```

Kudos for an excellent library and very useful for complex nested json structures.

Best,

raydf

**Comment by maiha** [comment]
Oh, cool! I'll implement it ASAP :)

**Comment by maiha** [comment]
Supported in version `0.3.0`.
https://github.com/maiha/jq.cr/blob/master/spec/nil_based_spec.cr

Thanks!

**Comment by ray-delossantos** [comment]
Thanks @maiha for a very fast solution. 

There's some discussion about removing JSON::Any in crystal. Do you believe that this library could work with JSON::Type casting directly? Right now you can use: 

``` crystal
test = JSON::parse_raw %({ "test" : "1" })
test.as?(Hash(String, JSON::Type)).try &.["test"]? || "0"
```

I'm evaluating the shard for using it in production and would like to have your feedback about the posibility of this change if the std lib is modified.

Best regards,

raydf

**Comment by maiha** [comment]
Oh, it's bad news! :no_good: 

I'll try to migrate `JSON::Any` to `JSON::Type` later.
But my first impression is that it's hard, or the new api won't be handy to use :)

At worst, `jq.cr` will be depend from crystal std lib, and live with current `JSON::Any` codes bundled.
Yep, love Crystal that written in Crystal ! :ok_woman: 

Anyway, I'll try it soon.
Thanks.

**Comment by ray-delossantos** [comment]
Hi @maiha 👍  : 

There's no decision about that yet, only an RFC:
https://github.com/crystal-lang/crystal/issues/3158

It's a nice idea to use the current JSON::Any code bundled in the shard if is deprecated from the std lib on the long run.

Thanks for the feedback,

raydf.
